# Project 6: Simple Neural Network Forward Propagation

**Objective:** Implement a simple neural network using the Iris classification dataset, perform forward propagation, apply activation functions, and display predicted Iris flower species.

## Task 1: Load and Prepare the Iris Dataset

The Iris dataset contains 150 samples, 4 input features, and 3 flower classes: Setosa, Versicolor, and Virginica.

In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
# Load Iris dataset
iris = load_iris()

X = iris.data
y = iris.target

print("Feature Names:")
print(iris.feature_names)

print("\nTarget Names:")
print(iris.target_names)

print("\nDataset Shape:", X.shape)
print("\nFirst 5 samples:")
print(X[:5])

Feature Names:
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Target Names:
['setosa' 'versicolor' 'virginica']

Dataset Shape: (150, 4)

First 5 samples:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [3]:
# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Standardize input features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])

Training samples: 120
Testing samples: 30


## Task 2: Build a Simple Neural Network

Network structure:

**4 Input Neurons → 5 Hidden Neurons → 3 Output Neurons**

In [4]:
# Initialize weights and biases
np.random.seed(42)

input_size = 4
hidden_size = 5
output_size = 3

W1 = np.random.randn(input_size, hidden_size)
b1 = np.zeros((1, hidden_size))

W2 = np.random.randn(hidden_size, output_size)
b2 = np.zeros((1, output_size))

print("W1 Shape:", W1.shape)
print("b1 Shape:", b1.shape)
print("W2 Shape:", W2.shape)
print("b2 Shape:", b2.shape)

W1 Shape: (4, 5)
b1 Shape: (1, 5)
W2 Shape: (5, 3)
b2 Shape: (1, 3)


## Task 3: Activation Functions

ReLU is used in the hidden layer and Softmax is used in the output layer.

In [5]:
def relu(x):
    return np.maximum(0, x)

def softmax(x):
    exp_x = np.exp(x - np.max(x, axis=1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

## Forward Propagation

Forward propagation passes the input through each layer to generate the output prediction.

In [6]:
# Input -> Hidden layer
Z1 = np.dot(X_test, W1) + b1

# Apply ReLU
A1 = relu(Z1)

# Hidden -> Output layer
Z2 = np.dot(A1, W2) + b2

# Apply Softmax
A2 = softmax(Z2)

# Predicted class
predictions = np.argmax(A2, axis=1)

print("Forward propagation completed successfully!")

Forward propagation completed successfully!


## Display Predicted Output

In [7]:
print("--- PREDICTION RESULTS ---\n")

for i in range(10):
    predicted = iris.target_names[predictions[i]]
    actual = iris.target_names[y_test[i]]
    print(f"Sample {i+1}: Predicted = {predicted}, Actual = {actual}")

--- PREDICTION RESULTS ---

Sample 1: Predicted = setosa, Actual = versicolor
Sample 2: Predicted = virginica, Actual = setosa
Sample 3: Predicted = versicolor, Actual = virginica
Sample 4: Predicted = versicolor, Actual = versicolor
Sample 5: Predicted = virginica, Actual = versicolor
Sample 6: Predicted = virginica, Actual = setosa
Sample 7: Predicted = setosa, Actual = versicolor
Sample 8: Predicted = versicolor, Actual = virginica
Sample 9: Predicted = virginica, Actual = versicolor
Sample 10: Predicted = virginica, Actual = versicolor


## Prediction Probabilities

In [8]:
for i in range(5):
    print(f"Sample {i+1}")
    print("Setosa     :", round(A2[i][0], 4))
    print("Versicolor :", round(A2[i][1], 4))
    print("Virginica  :", round(A2[i][2], 4))
    print()

Sample 1
Setosa     : 0.3479
Versicolor : 0.324
Virginica  : 0.328

Sample 2
Setosa     : 0.0
Versicolor : 0.0
Virginica  : 1.0

Sample 3
Setosa     : 0.0663
Versicolor : 0.7731
Virginica  : 0.1607

Sample 4
Setosa     : 0.3074
Versicolor : 0.3654
Virginica  : 0.3272

Sample 5
Setosa     : 0.1645
Versicolor : 0.1962
Virginica  : 0.6393



## Accuracy

Because this project demonstrates forward propagation with randomly initialized weights and does not train the network, the accuracy is only the result of the initial random network.

In [9]:
accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)
print("Accuracy Percentage:", round(accuracy * 100, 2), "%")

Accuracy: 0.06666666666666667
Accuracy Percentage: 6.67 %


## Result

A simple neural network was successfully implemented using the Iris dataset. Forward propagation was performed through the input, hidden, and output layers. ReLU activation was applied in the hidden layer and Softmax activation was applied in the output layer. The network generated predictions for Setosa, Versicolor, and Virginica Iris flowers.